### ISSUE TITLE
SVG in dark mode is hardly readable

### ISSUE THREAD

**Issue by vsemozhetbyt** [software-tools-in-javascript/stjs#27]
Google Chrome has an option "Force Dark Mode for Web Contents" (see chrome://flags/#enable-force-dark).

If this option is "Enabled", then SVG images in the book are hardly readable.

<details>
<summary>This is a screenshot:</summary>

![svg](https://user-images.githubusercontent.com/10393198/106381230-00030280-63c0-11eb-9783-4e5bfe4eafdf.png)

</details><br>

**Comment by gvwilson** [comment]
Thanks for filing this. The diagrams have to be usable in print as well, so filling in a white background will cause problems. I will look for a tool that reverses the colors of the SVG elements - is there a way to detect if the browser is in dark mode so that we know when to toggle the color?

**Comment by gvwilson** [comment]
Update: we can use
```
window.matchMedia('(prefers-color-scheme: dark)').matches
```
to detect dark mode in the browser - now I just need to find a way to toggle the SVG colors.
