### ISSUE TITLE
Figure 3.5 (temp objects) missing destructuring

### ISSUE THREAD

**Issue by robjwells** [software-tools-in-javascript/stjs#51]
In figure 3.5, on [temporary objects with named fields][f35], the code as shown will pass the temporary object as the parameter `left` and leave `right` undefined.

To match the comments in the body of `second`, where the fields of the object have been unpacked to the corresponding parameters, `second` should be defined so that the passed object is destructured, like so:

```js
const second = ({ left, right }) => { ... }
```

[f35]: https://github.com/software-tools-books/stjs/blob/46d38be1d2150f08d7572fcd5352dbf4a50db88e/async-programming/figures/temporary-named-fields.svg

**Comment by gvwilson** [comment]
thanks - I'll chase it down
