### ISSUE TITLE
unit-test: first appearance of `hope.js` doesn't match text

### ISSUE THREAD

**Issue by berquist** [software-tools-in-javascript/stjs#52]
In https://github.com/software-tools-books/stjs/blob/249327ee164209305d644b91b7a2aaeaa0f51561/unit-test/index.md?plain=1#L136-L138, the text mentions the class definition an export/instantiation, but the block is for the reporting methods.  On line 161 is the English description of the reporting functionality followed by the code.

**Comment by gvwilson** [comment]
thanks - I'll dig into it.
