### ISSUE TITLE
Menu bars don't work on mobile

### ISSUE THREAD

**Issue by mveytsman** [software-tools-in-javascript/stjs#8]
I opened the book in Safari on iOS and the navigation menu bars do not work.

I think this is because the menu is purely controlled by a `:hover` css selector which doesn't seem to register a tap. From my reading, some mobile devices send a hover event right before a click. When I test this in responsive mode in chrome, I see the menu when I click on the navbar, but it immediately registers as a click on the first menu item. On mobile safari on my phone I don't see the popup menu at all -- perhaps it's shown and disappears very quickly?

I'm not sure what the "correct" thing to do here I think it might be to use javascript instead of pure css to display the menu, and use an `onclick` when we detect a touchscreen.

**Comment by gvwilson** [comment]
My heart grows heavy upon hearing that iOS does not respect the `:hover` selector. If you have a favorite lightweight JavaScript implementation of pulldown menus, I'd be grateful for a pointer...

**Comment by gvwilson** [comment]
@mveytsman should now be fixed (click to pulldown rather than :hover).
